# Name of this GitHub Actions workflow.
name: Build

on:
  workflow_dispatch:
        
jobs:
  build-and-push:
    name: build and push to dockerhub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      
    - name: Build the Docker image
      run: |
        docker build . -t zadeeknss/nodeapp:1.0
        docker images
        
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Push the Docker image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: zadeeknss/nodeapp:1.0