# Name of this GitHub Actions workflow.
name: SLSA Level 2 Pipeline


on:
  workflow_dispatch:

jobs:
  build:
    name: build docker images with buildx
    runs-on: ubuntu-latest
    permissions:
      id-token: write 
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the Docker image
      run: |
        docker version
        docker buildx create --use --name=buildkit-container --driver=docker-container 
        docker buildx build --sbom=true --provenance=true -t zadeeknss/nodeapp-github:v1.0 .
        
        
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Push the Docker image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: zadeeknss/nodeapp-github:v1.0 

    - name: Login to GitHub
      uses: docker/login-action@v1.9.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.COSIGN_GITHUB }}
          
    - name: setup cosign
      uses: sigstore/cosign-installer@v3.1.1

    - name: Check install!
      run: cosign version

    - name: Sign the container
      env:
          COSIGN_EXPERIMENTAL: "true"
      run: cosign sign  --yes zadeeknss/nodeapp-github:v1.0 --force
