# Name of this GitHub Actions workflow.
name: SLSA Level 2 Pipeline


on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest

    permissions: {}

    name: Install Cosign
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.1
        with:
          cosign-release: 'v2.1.1'
      - name: Check install!
        run: cosign version
